### ISSUE TITLE
YAPC の影響力により、久々の Niigata.pm 開催の機運

### ISSUE THREAD

**Issue by Shinpeim** [NagaokaDevelopersStudy/Studies#14]
ヤップシーでうっかり「年内になんかやりますわ〜」発言してしまいましたので、口だけ番長にならないように Niigata.pm presents のテックトークを12月に行いたいと思っています。やりたかったしね！

せっかくなんで、12月に tech talk  × NDB 2014 という形で開催したいとか思っているのですが、12月の NDS  （in Niigata）ってすでになんか予定あります？  >  @civic @dictav @npoi 

もしまだ予定なければ街キャンでテックトークしてそのあと忘年会の流れで企画したいなと。

メインセッションは、

* 日本を代表するCPAN Authorと言っても過言ではない @hayajo さんにぜひ一本やっていただきたいです。
* JPAという団体が行っている「Perlハッカーを地方のPerl勉強会に送り込む渡航費を支援するぜ」という制度を利用して、東京からPerlハッカーをひとりお呼びして一本やってもらいたいなと思っています。これはわたしが渉外役やります。
* 先日のNDS in Niigata に参加されてた rito さんに一本やってもらえればありがたいなと思っていますが、わたし結局YAPCでご挨拶できなかったのでだれか rito さんに打診してみてほしいです。

あとのセッション、LTに関しては時間と相談しつつ調整の方向で。

忘年会に関しては、新潟県最強の幹事マンこと石橋さんにお手伝いしていただきたいと思っていますが、こちらはわたしから打診します。

みなさんいかがでしょう？

**Comment by dictav** [comment]
おつかれさまでした。
