### ISSUE TITLE
#NDS40は「初心者Day」にしませんか？

### ISSUE THREAD

**Issue by masaru-b-cl** [NagaokaDevelopersStudy/Studies#16]
気が早いですが、次々々回のNDS40は「初心者Day」にしませんか？という提案です。

最近のNDSは非常に濃くて、それはそれで好きなのですが、その分若干参加のハードルが高くなってるなぁと思いまして、ここらで初心者大歓迎な回を作ってみてはどうかなと思いました。

皆さんの意見を伺えればと思います。

**Comment by civic** [comment]
2/21に40回実施の予定日なのですが、どんな感じにしましょうかね。
別のイベントもかぶっているようなので、参加人数的にも少し不安があります。

**Comment by masaru-b-cl** [comment]
言い出しっぺのくせに完全ノープランで申し訳ないです……
 「はじめてのxxx」、 「xxx再入門」みたいなセッションテーマで固める、とかですかねぇ

xxxもあんまりエッジなのじゃなくて、比較的メジャーなものに限るとか。

**Comment by Nkzn** [comment]
12月にAndroid Studio 1.0がリリースされたばかりなので、Android再入門はやりたいですねえ。

ちょっとネットワークから落としてくる量がアレなので、要事前準備ですが。

**Comment by civic** [comment]
じゃあ、まさるさんのいうとおり、「はじめてのxxx」、 「xxx再入門」みたいなセッションテーマを募集する感じでやろうと思います。もう2週間ぐらいでリソース用意してもらえるといいなー。
NkznはAndroid再入門できそう？それはありがたいですね。

21日はデー潟ってのもかぶってるのでそのあたりも集まり的に心配なのですよ。

**Comment by Nkzn** [comment]
https://www.facebook.com/dgata2015

これかー・・・NSMCが噛んでるような噂を聞いたような？

**Comment by civic** [comment]
dictavさんがなんかそっちの発表とかするみたいですね

**Comment by civic** [comment]
つくりました！よろしくお願いします！
http://nagaoka.techtalk.jp/no40

**Comment by Shinpeim** [comment]
わたし今回出れないんですけど、「事務作業のための正規表現入門」みたいなセッションあるといいかもって思いました

**Comment by Nkzn** [comment]
ｱｯ脊髄反射でテーマセッションを申し込もうとしたけど、ちゃんと内容考えないと時間読めないやつだ・・・

**Comment by Nkzn** [comment]
@civic 懇親会が締切後ステータスになってます

**Comment by dictav** [comment]
あー、そうなんです。オープンデータデーとかで発表を頼まれていて、そっちに出ないといけないのです。yutacarさんの代わり。

**Comment by dictav** [comment]
@civic ちなみに、前回 nds meetup では Unity 入門的な内容をやりました。次回 meetup ではヘッドフォンアンプ入門的な内容をやります。

**Comment by civic** [comment]
@Nkzn フォーム直しました。ありがとうございます。
@Shinpeim 正規表現いいですね。置換ができるだけで事務処理捗りそう。参加できないの残念です。

**Comment by masaru-b-cl** [comment]
では、私は「仕事がはかどるOffice、エディターの操作入門」とでもしましょうか。
正規表現もその中でできたら。

**Comment by dictav** [comment]
おつかれさまでした！

**Comment by civic** [comment]
ありがとうございました :+1:
