### ISSUE TITLE
Firefox OS 勉強会の開催について

### ISSUE THREAD

**Issue by dictav** [NagaokaDevelopersStudy/Studies#20]
知っている方も多いかと思いますが、新潟オープンソース協会の ML に Firefox OS 勉強会の開催についてメッセージがありました。本間さんに許可をいただいたのでこちらにも転載します。
まだ日程などは決まっていないようですが、続報があればまたお知らせします。

> 初めまして、先日メーリングリストに登録させていただきました本間と申します。
> 
> どうぞよろしくお願いいたします。
> 
> 新潟での Firefox OS 勉強会の開催を検討しておりまして、よろしければ皆さんのお知恵をお借りしたくご連絡いたしました。
> 
> 私は Firefox OS のコミュニティに参加しておりまして、 Firefox OS に関する勉強会やイベント等を開催しています。
> 
> その中でも、ハンズオンと言いまして、 Firefox OS のアプリ入門と言いますか、実際に手を動かしてアプリ開発を学ぶ勉強会があります。
> 01/18 にも都内にてハンズオンが開催されました。
> https://atnd.org/events/60745
> 開催にあたり KDDI さんや Mozilla Japan さんから端末を提供して頂いています。
> 
> このようなハンズオンを新潟でも開催したいと思っております。
> 昨年末に Firefox OS 端末が日本でも発売されましたし、ちょうど良い機会だと思っています。
> 
> つきましては、 KDDI や Mozilla Japan より借用する端末台数を事前に伝える必要があるため、
> どのぐらいの人数の方が参加されるかおおむね把握できればと思っております。
> ですので、
> 
> 「私、参加します！」と思っていただけた方はご連絡いただけると助かります。
> 
> また、こういった勉強会はどの辺りで開催するのが普通なのでしょうか？
> 過去ログを拝見したところ、長岡技術科学大学さんの名前がありましたのでこちらにお願いするのが良いでしょうか？
> 
> 以上、よろしくお願いいたします。

**Comment by civic** [comment]
ここまでの経緯。

NDSでもFirefox OSハンズオンのアナウンスがありまして、最終的にほんぽーとで利用したいとのことになりました。つきましてはmeetupのほうでほんぽーとを利用する登録しているっぽいので、そこの名前で場所を借りてやらないか？という話です。

https://twitter.com/masap/status/570472655142457344

NDS長岡の方は、ほんぽーと利用登録はしてないですが、NDS meetupは登録しているみたいなので、そちら経由で使っては？と私が提案しました。

**Comment by masap** [comment]
ご確認いただきありがとうございます。はい、 NDS meetup での利用で構いません。

ところで、ちょうど今ほんぽーとから連絡があり、研修室 2 の方はネットワークが使えないとのことですが、皆さんはどうされていましたか？

**Comment by dictav** [comment]
ほんぽーとでは自前の WiMAX やモバイルルーターを持って行ってました。
正直、通信環境は良くないです。。。

**Comment by masap** [comment]
> ほんぽーとでは自前の WiMAX やモバイルルーターを持って行ってました。
> 正直、通信環境は良くないです。。。

そうでしたかー。クロスパル新潟は通信環境がありそうなのでそっちも検討してみます。

**Comment by masap** [comment]
クロスパル新潟取れました。やっぱりネットワークは必須だと思いますのでこっちにしようと思います。
ただ、午前と午後で別の部屋になってしまいますが...

**Comment by dictav** [comment]
了解です。
NDS meetup としてお手伝いできることはありますか？

**Comment by masap** [comment]
バタバタしてすいませんでした。

> NDS meetup としてお手伝いできることはありますか？

告知ページを作成してご連絡しますので、拡散いただければと思います m(_ _)m

**Comment by masap** [comment]
あ！ あと周辺で、ハンズオン後の懇親会に使えそうな店をご存知でしょうか？

**Comment by dictav** [comment]
いえいえ。
何かご協力できることがあれば言ってください。

**Comment by dictav** [comment]
> あ！ あと周辺で、ハンズオン後の懇親会に使えそうな店をご存知でしょうか？

これは普通の飲み屋さんではなくて、立食パーティーとかのイメージでしょうか？

**Comment by masap** [comment]
> これは普通の飲み屋さんではなくて、立食パーティーとかのイメージでしょうか？

いえ、普通の飲み屋です！

**Comment by dictav** [comment]
20人くらいならわりとどこでも大丈夫だと思いますよー

**Comment by masap** [comment]
> 20人くらいならわりとどこでも大丈夫だと思いますよー

はい。あの、「ここがうまい！」みたいな情報をいただければと。

**Comment by civic** [comment]
あれ、ほんぽーとじゃなくなったんですね。
@masap さんは、新潟の人じゃないんですよね?

**Comment by masap** [comment]
> あれ、ほんぽーとじゃなくなったんですね。
> @masap さんは、新潟の人じゃないんですよね?

はい。新潟の人ではないです。なのでクロスパル新潟予約時も NDS さんの名前を使わせていただきました。

**Comment by masap** [comment]
イベントページ公開しました！拡散いただければと思います！

https://firefox-os.doorkeeper.jp/events/21446

**Comment by civic** [comment]
ちょっとまってください。。。
NDSで予約取るならばこちらで予約取らないといけないのではないでしょうか？
ほんぽーとからクロスパルに変更した上にNDS名義で勝手に予約取られてしまうのは、ちょっと急ぎすぎじゃないでしょうか？クロスパルの利用料ってかからないのでしょうか？

**Comment by masap** [comment]
> ちょっとまってください。。。
> NDSで予約取るならばこちらで予約取らないといけないのではないでしょうか？
> ほんぽーとからクロスパルに変更した上にNDS名義で勝手に予約取られてしまうのは、
> ちょっと急ぎすぎじゃないでしょうか？クロスパルの利用料ってかからないのでしょうか？

ああ、すいません。。。
ほんぽーとでの名義借り OK だったのでこちらも OK と思ってしまっていました。。。
クロスパルの利用料はもちろんこちらでお支払いしますが、一旦キャンセルした方が良いでしょうか？

**Comment by dictav** [comment]
しょうしょうお待ちを

**Comment by dictav** [comment]
名義を貸すと言ったわけではなくて、NDSが代わりに場所を借りますよ、という話だったのだと思います。

予約は良いのですが、予約の先の利用申請は私の方で行いたいと思うのですが、どうでしょうか？
市に住所などを申請していますし、名前だけを使われるのにはやはり抵抗があります。

**Comment by civic** [comment]
基本的にはNDSとして取るのはOKなんですが、予約するのはNDSの人間がやらないいけないですし、使った時に問題が発生したりしたらNDSの責任になるため、NDS名義で借りてまったく違う人が使うというのは問題だと思った次第です。ほんぽーとについても同様でした。
とりあえずもう告知もされてますし、キャンセルするにしても、このままいくにしてもdictavさんの準備をまっておちついて準備していきましょう。

**Comment by dictav** [comment]
あ、ぼくの言葉足りない部分が捕捉されている

**Comment by dictav** [comment]
ちなみに、@masap さんの言う予約は「施設に電話して空きを確認して部屋を抑えた」という意味であすよね？その後、正式に利用申請を行う必要があると思います。
これはほんぽーとも公民館も同じだったので、クロスパルも同じだと思います。

**Comment by masap** [comment]
> 名義を貸すと言ったわけではなくて、NDSが代わりに場所を借りますよ、という話だったのだと思います。

> 基本的にはNDSとして取るのはOKなんですが、予約するのはNDSの人間がやらないいけないですし、
> 使った時に問題が発生したりしたらNDSの責任になるため、NDS名義で借りてまったく違う人が使う
> というのは問題だと思った次第です。ほんぽーとについても同様でした。

申し訳ありません、勘違いしておりました m(_ _)m

> 予約は良いのですが、予約の先の利用申請は私の方で行いたいと思うのですが、どうでしょうか？
> 市に住所などを申請していますし、名前だけを使われるのにはやはり抵抗があります。

> とりあえずもう告知もされてますし、キャンセルするにしても、このままいくにしてもdictavさんの準備を
> まっておちついて準備していきましょう。

では利用申請は @dictav さんの方にお願いできますでしょうか。
利用申請書のフォーマットは、クロスパルから私宛にメールで送られて来ますので、それを @dictav さんに転送します (github のプロフィールに書いてある email でよろしいでしょうか)。ご存知と思いますがクロスパルさんは Fax のみの受付なので、申込書に記入して 025-223-4572 に Fax をお送りしていただくことになります。

**Comment by masap** [comment]
>ちなみに、@masap さんの言う予約は「施設に電話して空きを確認して部屋を抑えた」という意味であすよね？
> その後、正式に利用申請を行う必要があると思います。
> これはほんぽーとも公民館も同じだったので、クロスパルも同じだと思います。

はい。利用申請はまだ行なっていません。

**Comment by dictav** [comment]
@masap 了解しました。プロフィールのメアドに送ってください。
あ、あと、これはできたらで良いのですが、イベントページのどこかにNDSが関係している旨を入れてもらうことはできますか？

**Comment by masap** [comment]
> @masap 了解しました。プロフィールのメアドに送ってください。

了解しました。

> あ、あと、これはできたらで良いのですが、イベントページのどこかにNDSが関係している旨を入れてもらうことはできますか？

「協賛」の項目に入れさせていただきました。

**Comment by dictav** [comment]
@masap ありがとうございます :smile: 

ちょっとバタバタしちゃいまいしたが、新潟で面白いイベントを企画してくれてありがとうございます。
ぼくも参加登録しましたので、設営準備や懇親会の準備などはぜひ手伝わせてください。
とりあえず懇親会の場所を決めましょうー
オススメのお店をピックアップしますねー

**Comment by civic** [comment]
ありがとうございます。それでは予定通りの日程できそうな感じですね。あらためて拡散告知してもOKかな？
申請手続き等は @dictav さんが行ってくれるようなのでよろしくお願いします。
@masap さんもわざわざ新潟で開催してくれてありがとうございます。私も日程調整して参加させていただきたいと思います。 :+1:

**Comment by masap** [comment]
> ちょっとバタバタしちゃいまいしたが、新潟で面白いイベントを企画してくれてありがとうございます。
> ぼくも参加登録しましたので、設営準備や懇親会の準備などはぜひ手伝わせてください。
> とりあえず懇親会の場所を決めましょうー
> オススメのお店をピックアップしますねー

@dictav こちらこそありがとうございます。設営とお店助かります。

> ありがとうございます。それでは予定通りの日程できそうな感じですね。あらためて拡散告知してもOKかな？
> 申請手続き等は @dictav さんが行ってくれるようなのでよろしくお願いします。
> @masap さんもわざわざ新潟で開催してくれてありがとうございます。私も日程調整して参加させていただきたいと思います。 

@civic ありがとうございます。ぜひ拡散していただければと思います。

お二人とも当日お会いできるのを楽しみにしております。

**Comment by dictav** [comment]
ビストロ椿
http://www.hotpepper.jp/strJ000773091/map/

海老の髭
http://www.hotpepper.jp/strJ000749181/map/

あたりがぼくの周りの評判も良いしオススメです。

**Comment by masap** [comment]
ありがとうございます！

**Comment by dictav** [comment]
@masap 利用者申請のFAX送りました。

もう参加者いっぱいになっちゃいましたねー

**Comment by masap** [comment]
@dictav FAX ありがとうございます！会場、もうちょい入れるので枠を 15 人に増やしました。

**Comment by dictav** [comment]
@masap 講師の方などの関係者も含めるとMAX何人がイベントに参加する予定でしょうか？
施設側に利用人数を提出しているので、問い合わせがあった時のために知っておきたいです。
あと人数が多くなってきたので懇親会参加のアンケートとって予約を早めにした方が良いかと思います。

**Comment by masap** [comment]
@dictav ご確認ありがとうございます。 MAX で 22 人を予定しています。懇親会、そうですね。 確認します。

**Comment by dictav** [comment]
@masap プロジェクタの利用について問い合わせがありました。午後からの306号室ではプロジェクタが使えないそうですが問題ないですか？必要であれば借してくれそうな人に聞いてみます。

**Comment by masap** [comment]
@dictav はい、午後はプロジェクタが全てふさがっている件は予約時に聞いていました。なので午後は pdf を配布してやろうかと考えていました。ただ、今どこをやっているかがわかると便利なので、借りていただけると助かります。

**Comment by dictav** [comment]
なるほど、なくても良いのですね。もし借りれたら連絡します。ただ、スクリーンの問題もあるので難しいかとは思います。

**Comment by masap** [comment]
@dictav 懇親会の予約ページを作りました。 https://firefox-os.doorkeeper.jp/events/21613 教えていただいた海老の髭さんです。

**Comment by masap** [comment]
@dictav 懇親会、ちょいと高いという意見がちらほら出ております... コースで一番安いやつを選んだんですが、都度注文の方が安く済んだりしますかね...

**Comment by dictav** [comment]
@masap 海老の髭さんを選んでいたので、ちょっと高級な方が良いのかと思っていました。
値段を気にするならビストロ椿の方が4120円なのでまだ無難かなーと思います。

**Comment by dictav** [comment]
もし、和食でもうちょっと値段を抑えた方が良い、ということであればそういうお店探します。
少人数なら都度注文も良いですが、10人くらいになるならコースの方が無難かと思いますよ。

**Comment by masap** [comment]
あの後 Mozilla さんから連絡が来て懇親会費をサポートしてもらえるとのことでしたので、コースにすることにさせていただきました。二転三転すいません。

**Comment by dictav** [comment]
@masap お！ありがとうございます！

**Comment by dictav** [comment]
明日ですね！
https://firefox-os.doorkeeper.jp/events/21613
懇親会は２人枠が余ってますが、当日声かければ集まりそう。

**Comment by masap** [comment]
一枠は KDDI さんが入るので、後一人集まるといいですなあ。

**Comment by dictav** [comment]
イベントの開場 8:50 になってますけど、施設の開場が 9:00 ですね

**Comment by dictav** [comment]
なんて言ってたら開きました

**Comment by dictav** [comment]
ありがとうございました！ぜひまたやりましょう！！
