### ISSUE TITLE
NDS meetup #5 のお知らせと開催場所について

### ISSUE THREAD

**Issue by dictav** [NagaokaDevelopersStudy/Studies#21]
3/14 (土) に第５回 NDS meetup を開催します。
メインセッション（ワークショップ）「プログラマティックにヘッドフォンアンプを作ろう」

開催場所
新潟市万代市民会館 406 和室

その他
https://github.com/NagaokaDevelopersStudy/Studies/blob/master/NDSMeetUp%235.md

~~「ほんぽーとで大丈夫じゃないか？」という話でしたが、大丈夫ならほんぽーとを取ります。~~

~~新潟市万代市民会館に工作室あったと思ったんだけどない？~~
~~http://www.city.niigata.lg.jp/chuo/shisetsu/manabi/shiminkaikan/bandai/kaikan05.html~~

@fcnt @daiquiri99 @npoi

**Comment by dictav** [comment]
NDSの方に移動
NagaokaDevelopersStudy/Studies#21

**Comment by dictav** [comment]
間違えました

**Comment by daiquiri99** [comment]
工作室は若者支援センター内の施設だったと思います。

**Comment by dictav** [comment]
411美術工芸室で工作ができることを確認しました。
大きな木製の木工用机もあるそうです。
また部屋の中には水道も付いています。

**Comment by dictav** [comment]
無事開催できました。
