### ISSUE TITLE
NDS #41 4/11について

### ISSUE THREAD

**Issue by civic** [NagaokaDevelopersStudy/Studies#22]
NDS40回を4月11日に予定しています。そろそろ告知しようかと思いますが、
テーマにたいしてなにかアイディアありましたら教えてください。

初心者Dayやった次なんですが、入学シーズンなので入学ネタと言う感じなのを考えてはみました。

**Comment by civic** [comment]
って書いてから、過去のIssueみてたんですが、TDDBC長岡を41にやろうかって以前(去年の9月）に話してて、「まだ先だから近づいてから考えましょう」ってしてました。。TDDBCを実施するときにそれをNDS41にするって話でしたが。。

**Comment by masaru-b-cl** [comment]
すんません、TDDBCはまた先送りさせてもらってよいですか？
年度末進行中に色々考えることできそうになくてですね……

> 入学ネタ

ありだと思います！

なお、参加できるかどうかは、今のところ未定です。

**Comment by dictav** [comment]
@masaru-b-cl #7 の放置よくないので一度 close しましょうか？ Studies とは別に repository 立てて、細かく issue を立てていったほうが良い気がしてきました。

**Comment by civic** [comment]
TDDBCの件、そういってもらえると助かります。やるつもりで準備してたらヤバいと思ったので。

ではなんらかのネタで通常開催したいと思います。

**Comment by dictav** [comment]
ぼくはネタ的に大丈夫なら iOS の UIAutomation テストでちょっと話したいです

**Comment by civic** [comment]
テーマはあくまで発表ネタを考えやすいように誘導してるだけなので、テーマ外でも問題なしというスタンスですので安心を :smiley: 
もしくは「UIAutomationテストへの入学」とかでもありかと :sweat_smile:

**Comment by dictav** [comment]
では UIAutomationテストについて話します :)

**Comment by masaru-b-cl** [comment]
> @masaru-b-cl #7 の放置よくないので一度 close しましょうか？ Studies とは別に repository 立てて、細かく issue を立てていったほうが良い気がしてきました。

その方向でお願いします。

**Comment by civic** [comment]
遅くなりましたが、募集開始しました！http://nagaoka.techtalk.jp/no41

**Comment by Shinpeim** [comment]
LTで応募してましたが、30分もらってもいいでしょうか。内容はふつうに技術的なやつしゃべりますのでタイトルは「新潟を卒業する話（ふつうに技術的な内容）」としておいていただけるとなおのことありがたいです。

**Comment by civic** [comment]
はい、30分コースへの変更承りました！

**Comment by dictav** [comment]
お疲れ様でした。
