### ISSUE TITLE
6/13 NDS42

### ISSUE THREAD

**Issue by civic** [NagaokaDevelopersStudy/Studies#24]
1ヶ月前なのでそろそろ準備しようかと。
なにかネタありますかねー。

**Comment by masaru-b-cl** [comment]
うぁ、別の用事と日程がカブった……
参加するとしたら遅刻していきます、たぶん。

で、テーマですね。

個人的には、@Nkzn くんにdocomoとのアレ話せる範囲で聞いてみたいなー

**Comment by npoi** [comment]
アレの話ですね…アレの…

**Comment by Nkzn** [comment]
ちょうどアレのAndroid版作ってるとこなので、どういうコンセプトのプロダクトなのか話せる程度のネタは持ってますね

**Comment by civic** [comment]
ぜひウォーターセルのニュースの話もしてもらいたいですね。
メインテーマ的にしてしまうと、ぜんぶウォーターセルの話になっちゃうので、テーマにはしづらいかなぁ。
それとも全セッションのハイジャックしちゃえる？？

**Comment by Shinpeim** [comment]
行ける可能性が微レ存

**Comment by civic** [comment]
:tada:

**Comment by Nkzn** [comment]
全セッションハイジャックできるほどのネタはない気がする・・・？

**Comment by civic** [comment]
じゃあなにかうまく取り込めるようなテーマを考えますねー

**Comment by hayajo** [comment]
:confetti_ball:

**Comment by civic** [comment]
ということでよろしくお願いします！！
http://nagaoka.techtalk.jp/no42

**Comment by dictav** [comment]
おつかれさまでした
