### ISSUE TITLE
10/17 NDS JAWS-UG回の予定

### ISSUE THREAD

**Issue by civic** [NagaokaDevelopersStudy/Studies#26]
@wokamoto さんの協力でラスベガスのAWS イベント re:invent の報告をしてもらえることになっています。
あとは、 @npoi くんもネタ持ってそうだし、「JAWS-UGやろう」的な流れになっています。

ゲストを呼ぶ的なことは残念ですが、re:inventが行われた直後であちこちに呼ばれている時期もあって難しいだろうとのことです。

参加者の方々の発表でJAWS-UG第2回が開催できたらいいなと思います。
新たな参加者に「こんなのやってるんだ！」って知ってもらいたい告知のために、発表内容がもっと欲しいところです。告知前の「発表するよネタ」をぜひ挙げてください。

**Comment by Shinpeim** [comment]
日付によっては参加したく候

**Comment by Shinpeim** [comment]
あっ10/17ってかいてあった

**Comment by Shinpeim** [comment]
:bow:

**Comment by civic** [comment]
はい、10/17です。最近、告知後にネタ集め開始していたので、告知時点でのネタが少ないと「面白そう！」って思われにくいんじゃないかと思ってます。開始時点で2,3本は決まった状態にしたいです。
ご協力よろしくお願いします！ :pray:

**Comment by hayajo** [comment]
個人になるか会社になるか @npoi くんにお任せするかわかりませんが、「Docker + AWS（仮）」で話そうかなーなんて考えてます。おそらく30分ぐらいかなーと。
何卒よしなに願い申し上げ候。

**Comment by Shinpeim** [comment]
いければそして仕事が順調にいけば、「ScalaとSQSで作るジョブキューシステム」で発表しますにゃん（なにがにゃんですか）

**Comment by civic** [comment]
やった! @hayajo さん個人、ウ社、 @npoi くんの3本確定っすね！さらに @Shinpeim さんもSQSネタで、4本かーやったー

**Comment by hayajo** [comment]
いやまて

**Comment by Shinpeim** [comment]
@hayajo さんが5本くらい喋ってくれますよ

**Comment by masaru-b-cl** [comment]
@Shinpeim さんくるなら懇親会だけでも参加したいなー

（10/10（土）に.NETのやるんで、本編はたぶん無理）

**Comment by hayajo** [comment]
@Shinpeim まてまて

**Comment by hayajo** [comment]
誰かLambdaについて話して欲しい感じです。私まったく知らないので。
@npoiくんに相談だ。

**Comment by civic** [comment]
場合によっては、前半とかに初心者向けなAWSチュートリアル（前やったような感じの）をやって、学生・新規参加者を集めつつ、発表できるぐらいの人たちはお手伝い担当 or 後半のみ参加 とかでもいいかなって思います。
チュートリアル用の体験チケットぐらいはくれるんじゃないかな？ないかな？

**Comment by dictav** [comment]
:construction:

**Comment by Shinpeim** [comment]
githubの emoji まわりバグってるきがする 
![image](https://cloud.githubusercontent.com/assets/876988/9593589/518bb848-508b-11e5-9def-956f54de085b.png)

**Comment by civic** [comment]
あ、僕も少し「？」って思ってたんだ。dictavさん「資料作成中って意味なのかな」って思ってました。
今見るとくす玉だ。

**Comment by npoi** [comment]
会社としてなにか発表ができるかは分からないですが、Lambdaネタでちょっとしたのをやりたいと思います。
よろしくお願いします。

**Comment by dictav** [comment]
絵文字、自分のタイポかと思ったけど違ったかな？ :confetti_ball:

**Comment by Shinpeim** [comment]
あー、あとから編集したんすね

**Comment by yuukigoodman** [comment]
お久しぶりです。丹内です。僕にも何か話させて頂きたいです。「チーム開発とAWS」とかそんなタイトルでElasticBeanstalkやCloudFormation周りを

**Comment by civic** [comment]
@yuukigoodman 丹内くん来てくれるのありがとう！ぜひお願いします。
事前発表するのに十分なくらいセッションがあつまりそうですね！みなさんありがとうございます

**Comment by civic** [comment]
告知ページを作成しました！発表予定のみなさん、よろしくお願いします！
http://nagaoka.techtalk.jp/no44

**Comment by civic** [comment]
募集も開始しました！ https://nagaoka-study.doorkeeper.jp/events/31333
発表者の方も登録お願いします。あと学生とかにも告知するチャンスがあるかたはぜひ新しい参加者を増やすことに協力お願いしまっす！
学生なんかでAWS初めてな感じが多ければ、AWSことはじめ的なセッションも欲しくなるかもですね。

**Comment by dictav** [comment]
:confetti_ball:

**Comment by civic** [comment]
参加者募集に拍車をかけるため、発表内容について軽い概要（100字程度）とか、この発表的な見どころ的なものを、公式アカウントから紹介,告知していきたいと思います。発表予定の方にちょこちょこ聞いていこうと思いますが、さしあたって @Shinpeim さんならきっと準備万端だろうから、見どころ、概要なんかサクッとお答えできますか？ :pray:

**Comment by Shinpeim** [comment]
厳しい（厳しい）

準備ぜんぜんできてないっす！ただ予定としては、

* ジョブキューってなーに
* SQSってなーに
* SQSを使ってジョブキューを実装する際の注意点など


となる予定です

**Comment by civic** [comment]
ありがとう！忙しいそうな中協力頂いて感謝感謝です。

**Comment by dictav** [comment]
すごい勉強になりました
ありがとうございました！
