### ISSUE TITLE
12/5 NDS45 NDB2015 

### ISSUE THREAD

**Issue by civic** [NagaokaDevelopersStudy/Studies#33]
2015年最後のNDSを12/5に開催します。
テーマ的には未定なんですが、何か推し案あったら意見下さい。特になければ2015年総括的に
「2015年やったこと報告」みたいなテーマでも設けようかと思います。

懇親会は年末なので新潟Dev忘年会2015（NDB2015）として店でやろうと思います。新潟のDevの皆さん参加して下さい。あっデザイナーでもいいです。

店なんで人数早めに決めたいとこですが、忘年会シーズンもあるので20名くらいでとりあえず十字路とか確保しようかとおもいます。
それとも学生とか考えるとまたマチキャンでやった方がいいのかなって気もしてます。
店なら4000円くらい。マチキャンなら2000円くらい。

**Comment by masaru-b-cl** [comment]
> 2015年やったこと報告

:+1: 

私はLTかなんかで「Niigata.NET」について話そうかな。

> それとも学生とか考えるとまたマチキャンでやった方がいいのかなって気もしてます。

相変わらず私がNDSへの参加率が低いのですが、最近も学生さん結構いらっしゃる感じですか？
であれば、まちきゃんで第1部、どっかで第2部ってのはありですね。

**Comment by civic** [comment]
学生は減りましたね。2,3人いるかどうかという感じです。
まちキャンでやるなら関要くらいにはしたいんですが買い出しとか面倒で配達業者でもいれば助かるんですが。

**Comment by civic** [comment]
店に探してみてもどこも満席で見つからなくて、もしあってもキツキツな座敷になりそうなんで、忘年会らしくなくて申し訳ないんですが、まちキャンで開催することにします。みなさんの準備・片付けご協力お願いします。
ちなみに時間帯ずらしても混んでそうなので、2次会すら危ういと予想してます。まちキャンでじっくり過ごしましょう。
