### ISSUE TITLE
2/20 NDS46

### ISSUE THREAD

**Issue by civic** [NagaokaDevelopersStudy/Studies#36]
2016年 最初のNDSを2/20に実施します。
https://sites.google.com/site/ndssite/no46
内容まだ決まってないのですが（やばい！）、ご意見あればよろしくお願いします！

なにも決まってないと意見しにくいと思うので、私からテーマ案を１つ挙げておくと、
「スクリプト言語ネタ」ってことで、各種言語なんかを特集して話したいことを話してもらう会をやろうかと思います。

**Comment by masaru-b-cl** [comment]
未YAuthですが、参加できるなら「C#がスクリプト言語になったよ！」な発表したいと思います。

**Comment by Shinpeim** [comment]
しゃべりたい

**Comment by civic** [comment]
告知しておいて準備忘れてました。スイマセン　:bow: 
それでは、そんなテーマで作成しておきますね！

**Comment by hayajo** [comment]
Goでしゃべります
