### ISSUE TITLE
NDS50 開催日,内容について

### ISSUE THREAD

**Issue by civic** [NagaokaDevelopersStudy/Studies#37]
第50回NDSを12月あたりに開催予定です。
開催についていろいろ検討しました。
- 普通開催案
  - 場所は？
  - 店は？
- 泊まり案
  - スノーピーク借りる →冬だから無理では
  - 旅館など → 忘年会シーズンで高い
  - ギークハウスの新物件 → まだ設備が整っていなそうか

で、泊まり案も魅力的ではあったのですが、時期的にいろいろ難しい点もあるので今回はとりあえずいつもみたいな形でやろうかと思います。寒くない時期に合宿的なノリで企画したいと思います。

で、開催日と場所なんですが、まちなかキャンパスがなかなか取れなくて現在調整中です。確保できているのが12/10の創作交流室です。定員は多い部屋なのですが、島タイプのテーブルなので意外と人数使えなかったりする問題がありますので、レイアウト変更するなどを検討したいと思います。

また12/10はYAPC Hokkaidoとも開催日が被っているため、この日で良いのかという心配もあります。

本来であれば早めに日にちを確定させて告知したいところですが、他の場所が取れたら違う日という案もあると思っているので、ご意見あればお聞かせください。

**Comment by hiro55bs** [comment]
いしばしです。12月10日(土)空いてます。
会場が確保できなければまた弊社をご利用いただいても構いません。

**Comment by civic** [comment]
こちら、11/19(土)のアオーレ市民交流ホールDも確保できました。
アオーレ市民交流ホールDは使ったことがないのですが、まちキャンの交流ルームなみに広いようなので十分講演会などができる環境かと思います。
http://www.city.nagaoka.niigata.jp/shisei/cate05/ao-re/floor_f3e.html （ガラス張りの結構目立つ場所）

12月にすることにこだわりがあるわけではないので、イベントの重複などなくできるかぎり多くの人が集められる日に実施したいと思います。「11.19の方が良い」「12.10が良い」といった意見でも聞かせてもらえればできるだけ反映させたいと思います。
（要望が競合して応えられない場合は申し訳ありません）

**Comment by masaru-b-cl** [comment]
まだ会場抑えようとしている段階ですが、11/19（土）はNiigata.NETも開催を予定しています。
なので、個人的には12/10の方がカブらなそうでよいです。
（とはいえ、11/19の確保難しそうな感じではあります）

**Comment by civic** [comment]
日程が被るのは困りますよね…。
NDS49もOSC長岡と被って泣く泣く日程ずらしたので今回はそうならないように早めに決めておこうと思ったのですが。
.NETはどのぐらいの日程確定ぐあいなんでしょう？できればNDSとしても日程は被りたくありません。

**Comment by masaru-b-cl** [comment]
今回は他の方に会場任せているのですが、仮押さえしたあと本申し込み手続きをしたという連絡がない状態です。

いっそのこと.NET DayにするというウルトラCは……ダメですよね:sweat:

**Comment by civic** [comment]
まあ.NET Dayにするでもいいのですけども、、
わかりました。ではNDSは当初の予定通り12/10にすることにします。
決めないことには前に進めないのと日程被りは避けたいので。イベント情報ありがとうございます。

**Comment by masaru-b-cl** [comment]
こちらの都合なのにすみません。ちゃんと確定したら、何らかの形で情報共有しますね。

**Comment by civic** [comment]
いえいえ。会場よければアオーレ使いますか？
必要ならご連絡ください。

**Comment by masaru-b-cl** [comment]
ありがとうございます。お言葉に甘えて、使わせていただきます。
手続等必要なことがあればまた連絡ください。

**Comment by civic** [comment]
ネット予約できるのですよね？ではタイミング合わせてキャンセルするので即取るという形でお願いします
2016年9月30日(金) 7:54 masaru-b-cl notifications@github.com:

**Comment by masaru-b-cl** [comment]
ネット予約できないです……登録してないので。
昼休みにアオーレ行って利用者登録申請してきます。

**Comment by masaru-b-cl** [comment]
利用登録完了しました。

**Comment by civic** [comment]
時間についてはDMで調整させてください。
