### ISSUE TITLE
NDS56 実施案（ハンズオン可能かどうか）

### ISSUE THREAD

**Issue by civic** [NagaokaDevelopersStudy/Studies#38]
NDS56を7/7に開催予定です。今回やりたいこととしては新規の参加者を増やしたいと思っています。
以前、他の勉強会に参加したときに「NDSは難しい」という意見があったので、前回初心者回をやったあとではありますが、初心者向けにハンズオンなんかを開催したいと思ってます。

そこで、2時間の軽いハンズオンを、2本立てくらいでできればいいなぁと思っていますが、ハンズオンは準備もわりと大変なので、ハンズオンを実施してくれる人や協力者が集まったらやるつもりです。
ハンズオン実施者の準備も必要なので、なるべく早めに（6/16までには...)決定したいところです。

一応、Twitterで声に上がった意見としては、以下の感じです。

- TDD (まさるさん立候補。ただし、まだNDS自体の参加が確定していないので保留）
- Vuejs （sakapunさん。他のVueLaravel勉強会で実施済みのもの）
- Scala（しんぺいさん。ちょっと新規参加者向けではないかという懸念あり）

Git的なのをまたやってもよいかと思いますし、プログラムから少し離れたほうがより対象者が広がるかなぁと考えております。
「私がこういうのやりたい」「こういうのに参加したい」「準備協力したい」といった意見があればぜひ意見を聞かせてください。

**Comment by dictav** [comment]
Nintendo Switch Labo とか。

久しぶりに参加したい気持ちであります。お手伝いします！

**Comment by civic** [comment]
Switch Laboの人集まりそうですけど、どうやって実施するのか..
ぜひまた来てください！

**Comment by NPoi** [comment]
候補としては、Python boot campの教材を使ったPythonのハンズオンなどもあるかもしれないです。

ただ、ちょっと時間掛かりすぎな気もしますし、NDSでやる必要性というのも弱いですかね。

**Comment by civic** [comment]
参加者集めという意味では、内容はPythonハンズオンでもよいのですが、2時間程度だと確かにボリュームが多いですね。。すこし削ればできるのかもですが。

**Comment by civic** [comment]
色々ご意見ありがとうございました。
準備期間も少なくなり、確かにやれそうなハンズオンの用意ができなそうなので、ハンズオン実施は取り止めとしたいと思います。
ご協力ありがとうございました。
